name: build
on:
  push:
    branches:
      - deploy-c2c-dev

jobs:
  all-in-one:
    name: Aqua scanner
    runs-on: ubuntu-latest
    environment: c2c-dev
    env:
      AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
      ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
      ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
      IMAGE_TAG: ${{ github.sha }}
      AQUA_KEY: ${{ secrets.AQUA_KEY }}
      AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
      TRIVY_RUN_AS_PLUGIN: 'aqua'
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AQUA_URL: ${{ secrets.AQUA_URL }}
      CSPM_URL: ${{ secrets.CSPM_URL }}
      
    permissions:
        id-token: write
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Aqua scanner
        uses: docker://aquasec/aqua-scanner
        with:
          args: trivy -d fs --scanners config,vuln,secret . --sast
          # To customize which severities to scan for, add the following flag: --severity UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL
          # To enable SAST scanning, add: --sast
          # To enable npm/dotnet non-lock file scanning, add: --package-json / --dotnet-proj  
      - name: Build image locally
        run: |
          docker build -t "$ECR_REGISTRY/$ECR_REPOSITORY:vulhubredis$IMAGE_TAG" .
      - name: Manifest Generation
        run: |
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          if ! cat install.sh.checksum | shasum -a 256 ; then
            echo "install.sh checksum failed"
            exit 1
          fi
          sh install.sh
          rm install.sh install.sh.checksum
          billy generate \
              --access-token "${{ secrets.GITHUB_TOKEN }}" \
              --aqua-key "${{ secrets.AQUA_KEY }}" \
              --aqua-secret "${{ secrets.AQUA_SECRET }}" \
              --artifact-path "$ECR_REGISTRY/$ECR_REPOSITORY:vulhubredis$IMAGE_TAG"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          #role-session-name: GitHubActions
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
     # - name: Native docker ECR login
      #  id: docker-ecr-login
       # run: |
        #  result=$(aws ecr get-login-password --region $AWS_REGION| docker login --username AWS --password-stdin ${{ env.ECR_REGISTRY }})
         # echo "Login Result: $result"
      - name: Tag and push image to Amazon ECR (+latest)
        run: |
          docker tag ${ECR_REGISTRY}/${ECR_REPOSITORY}:vulhubredis${IMAGE_TAG} ${ECR_REGISTRY}/${ECR_REPOSITORY}:vulhubredislatest
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:vulhubredis${IMAGE_TAG}
          docker push ${ECR_REGISTRY}/${ECR_REPOSITORY}:vulhubredislatest
